version: 2

defaults: &defaults
  working_directory: ~/project/view-observer
  docker:
    - image: circleci/node:7.10

jobs:
  install:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-view-observer-{{ checksum "package.json" }}
          - v1-view-observer-

      - run: npm install

      - save_cache:
          key: v1-view-observer-{{ checksum "package.json" }}
          paths:
            - node_modules
      
      - persist_to_workspace:
          root: ~/project
          paths:
            - view-observer

  test-cover:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/project

      - run: npm run test

      - run:
         name: report coverage stats
         command: ./node_modules/.bin/codecov

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - test-cover:
          requires:
            - install
