version: 2

defaults: &defaults
  working_directory: ~/project/view-observer
  docker:
    - image: circleci/node:7.10

jobs:
  install:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-view-observer-{{ checksum "package.json" }}
          - v1-view-observer-

      - run: npm install

      - save_cache:
          key: v1-view-observer-{{ checksum "package.json" }}
          paths:
            - node_modules
      
      - persist_to_workspace:
          root: ~/project
          paths:
            - view-observer
